ShiYue_Channel=16
ShiYueSERVER_URL=http://sdk.shiyuegame.com/
ShiYue_PAY_PUBLICKEY=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcN8q24KDv/whbvf/xB04h0jswzyLiRu2YbzRDG513GKXAAlo7iPscoaLPICtkJSr5PuIWcnEZdcG7bsyF07TWTm2FWMAFL/oX7ZziIS1S6gaEzjxZcH9ruulLtFWWyhYCCIxc4WKSmYGZ/Zmzaa2NexM+brlYdE848IyOZjYEH1kGhCD0cmhMl2hpBRozFDMDEv7KGkfArXu6nAJ48Pz7ciPuZ3l+eZUPjVTRwOcgQ8CGTccSOaMkzWQW56SVCeMFdfR3OUAyXbh9uLfAQ5FWa3lwDz/SLN3TDnPyojCmkAn2nYoPLtVdHnANSsXv1dYGdsomAUYcsrv5qHjk9otdAgMBAAECggEAa5IBPpW5Z6JPZekItacY3mKAMVZtNtToyJZBlCpQH9X1WTaM9xnxd8no6n5PU8roE/pInCho4MPpz3HPC+wfILQMwZ9ZpO8LnlaeVMNaDW9tob/QMOxIAcq6nRVI3bB3UaT1U4VxDiVX7m23f7E2aq7c9plFhlTCQhEWx5Rb/GSfpevtxtDj55UajT2ehrXn3SfrOi5aflnZLQLY6zeg2hhE1v7vhAzzgmL2NubII2NcQ6nwGEsBZykVq3jMn28o9QP4f2SVddFNjS8IE9kCGVl8aZvT1dwyMTaO3uA9XeNiyoVRIPO4aHqo3kC/wuVvv62K+XdzA8xKDn3vlnllIQKBgQDyqYAmsSEjOpF5ITsynt+637Cxfxw7qoYrxFtJQD2ROKpzkTtf2bYRbIJYF4IMsYtz8oyk8wkMh0zGX0BX5jlLMDvHsO2Nx04ORh/+gJrg3hH1uWmy64g0csl6HGjM9s8pMlrsYNy5NXtxUZeISckaLs24Ltoxg+eOMiGqU3s+tQKBgQDoUnqtABl0aErFB+St+ca3n7oqy024sNcJaF/QwWKMmxE0Hcab+5a2QO1QgKkzpJUBFm+LW3PX7GLu+dbAYtC/+acsrPw+DeSXabUiTY5+DkSg/y7sS/QsQ3uuWBEJLaPoiEBxkZbxcU1e/aT5eJ5djUOqiQ7YsPMNQiQN7FtbCQKBgDzyLWmKW1RJxXeyzPdtx6tbuzkZP7IMph4f9v1y0QPEQ6s68rqkJ4JAyovte5BMl0XLyV80WzV2VeYMzlBFVmZ3+suwuDk/sW8MVcTJ8BxCKiiZJN73IQJrQgcVU40HAAjMyOFNgqJRuGtBntlwDr4wuyJjQhHlmyavmJz60p1xAoGBALQ4H1AKzrQ9nxrfN6c6JswVDR7bXSxTikyS+hj/m0pFlH/gRUyFS3GQRkf3tsoH90rDs73gMKokhs6pYs0VGqiBqwx+GKKutlA6wTeeAFaLDPPzYNwPQ5f+tXgWewiqrgbZg1xWO0iKwyFYE90uk3Mw/XfSIIE6KyFy2HMwkeG5AoGBAIzBRaBGj6VqqQ1dhRwKH3EAUsCGzHo8ObdY+W2uC/ZTiLx9viDRIOKPYenKBSs2/5PWrgHRRvEAjD92OAweOCmTH1kJDrkVwutO1Jlb4EB7rFEiJF/lto2bNt8nfSUQ8QIefSkP13Fv+FSZl+HdhKX8CFO9SwLmihwkgzAoAvfn
ShiYue_Sub_Channel=18
LeLanProjectId=11
LeLanAppId=374
LeLanSecret=Xt7ebuJzmZPb8Q1lqGPNoy5E
LeLanOneKeyLoginAPPID=SY8235217455
LeLanOneKeyLoginAPPSecret=1haRukOKxFvpHOa5NyZYWMFkDV2UGZtd
BURIED_LOG_REPORT_OPEN=false
BURIED_LOG_REPORT_URL=https://sdk-upload.shiyuegame.com/user/entry
SCREEN_ORIENTATION=PORTRAIT
U8_SDK_VERSION_CODE=0
U8_Channel=57
U8_APPID=4
U8_APPKEY=7ae4bf7c7c6f0f816e62c8fa6b4030ed
U8_SDK_SHOW_SPLASH=false
U8SERVER_URL=http://192.168.2.88
U8_ANALYTICS=false
